export const SEO_KEYWORDS = [
  "Innov'Industry 2026",
  "Innov'Industry ENSA Fès",
  "journée pédagogique ENSA Fès",
  "journées pédagogiques 4 filières",
  "journée industrielle JESI",
  "journée industrielle ENSA Fès 2026",
  "forum étudiant ENSA Fès",
  "salon étudiant ingénieur Fès",
  "conférence ENSA Fès 2026",
  "Innov'Industry inscription",
  "Innov'Industry programme",
  "Innov'Industry intervenants",
  "Innov'Industry sponsors",
  "Innov'Industry compétition",
  "Innov'Industry orientation",
  "journée portes ouvertes ENSA Fès",
  "forum ingénierie Fès 2026",
  "networking ingénieur Fès",
  "forum emploi ingénieur Maroc",
  "ENSA Fès",
  "ENSAF",
  "JESI ENSA Fès",
  "club JESI",
  "ingénieur état ENSA Fès",
  "formation ingénieur Fès",
  "filières ENSA Fès",
  "génie informatique ENSA Fès",
  "génie électrique ENSA Fès",
  "génie industriel ENSA Fès",
  "génie civil ENSA Fès",
  "bac+5 ingénieur Fès",
  "école ingénieur Fès",
  "powerup club ENSA Fès",
  "vie étudiante ENSA Fès",
  "actualité ENSA Fès",
  "orientation filière ingénieur Maroc",
  "choisir filière ingénieur ENSA",
  "débouchés génie informatique Maroc",
  "carrière ingénieur Maroc",
  "emploi ingénieur Maroc 2026",
  "stage ingénieur Fès",
  "stage ingénieur Maroc 2026",
  "salaire ingénieur Maroc",
  "marché emploi ingénieur Maroc",
  "offre emploi ingénieur Fès",
  "débouchés génie civil Maroc",
  "débouchés génie industriel Maroc",
  "débouchés génie électrique Maroc",
  "compétences ingénieur 2026",
  "intelligence artificielle métiers Maroc",
  "data science emploi Maroc",
  "Capgemini Maroc recrutement",
  "Safran Maroc ingénieur",
  "Alten Maroc stage",
  "entreprise partenaire ENSA Fès",
  "partenariat industriel ENSA Fès",
  "entreprise tech Fès",
  "Green Energy Park Maroc",
  "Cité innovation Fès",
  "UM5 Rabat partenariat",
  "écosystème startup Maroc",
  "multinationale Maroc ingénieur",
  "recruteur ingénieur Fès",
  "intelligence artificielle Maroc 2026",
  "machine learning Maroc formation",
  "data science Maroc étudiant",
  "cloud computing Maroc ingénieur",
  "cybersécurité Maroc formation",
  "IoT Maroc ingénieur",
  "industrie 4.0 Maroc",
  "transformation digitale Maroc",
  "énergie renouvelable Maroc ingénieur",
  "smart city Maroc",
  "ingénierie logicielle Maroc",
  "automatisme Maroc ingénieur",
  "réseaux télécommunications Maroc",
  "lean manufacturing Maroc",
  "supply chain Maroc ingénieur",
  "hackathon ENSA Fès",
  "quiz ingénieur Maroc",
  "challenge étudiant Maroc",
  "pitch startup étudiant Maroc",
  "club robotique ENSA",
  "club développement web ENSA",
  "club énergie ENSA",
  "association étudiante ENSA Fès",
  "workshop étudiant Fès",
  "masterclass ingénieur Maroc",
  "simulation entretien étudiant",
  "atelier CV ingénieur Maroc",
  "compétition étudiante Maroc",
  "comment choisir sa filière à ENSA Fès",
  "quelles sont les filières de ENSA Fès",
  "programme journée pédagogique ENSA Fès 2026",
  "comment s'inscrire Innov'Industry 2026",
  "débouchés filière génie informatique ENSA Fès",
  "meilleure filière ingénieur au Maroc",
  "salaire ingénieur débutant Maroc 2026",
  "comment trouver stage ingénieur Fès",
  "entreprises qui recrutent ingénieurs Fès",
  "événements étudiants Fès mars 2026",
  "compétition ingénieur Maroc 2026",

  // Nom de l'événement — variantes
  "Innov'Industry 2026",
  "InnovIndustry 2026",
  "Innov Industry 2026",
  "INNOV'INDUSTRY 2026",
  "Innov4Industry 2026",
  "Innov'Industry ENSA Fès",
  "Innov Industry ENSA",
  "journée innovation industrielle 2026",
  "journée innovation industrielle Fès",
  "journée innovation industrielle ENSA",
  "J2I 2026",
  "J2I'2026",
  "J2I ENSA Fès",
  "journée industrielle ENSA Fès",

  // JESI
  "JESI 2026",
  "JESI ENSA Fès",
  "journées étudiantes sciences ingénierie",
  "journées étudiantes ENSA Fès",
  "JESI PowerUP",
  "JESI Fès 2026",
  "JESI Génie Industriel",
  "journée étudiante ingénierie Fès",

  // Campus Indus
  "Campus Indus 2026",
  "Campus Indus 4",
  "Campus Indus ENSA",
  "Campus Indus IEC",
  "Campus Industriel Fès",
  "Campus Indus 4ème édition",

  // Innov'Tech
  "Innov'Tech 2026",
  "InnovTech ENSA Fès",
  "Innov Tech MTZ",
  "Innov Tech mécatronique",
  "innovation technologique Fès 2026",

  // Innov'Dom Challenge
  "Innov'Dom Challenge",
  "InnovDom Challenge",
  "Innov Dom Challenge 2026",
  "Innov'Dom Challenge 2ème édition",
  "compétition Innov'Dom",
  "compétition technologique ENSA Fès",
  "compétition innovation industrielle Maroc",
  "compétition projets innovants Fès",
  "compétition ingénierie ENSA",
  "challenge innovation ENSA Fès",
  "challenge technologique Maroc 2026",
  "challenge génie industriel",
  "appel à candidatures ENSA Fès",
  "appel à projets innovants Maroc",
  "concours innovation Fès",
  "concours ingénierie Maroc 2026",
  "concours technologique étudiant Maroc",

  // Institution
  "ENSA Fès",
  "École Nationale Sciences Appliquées Fès",
  "ENSA Fès 2026",
  "ENSA Fès événement",
  "ENSA Fès innovation",
  "USMBA Fès",
  "Université Sidi Mohammed Ben Abdellah",
  "USMBA innovation",
  "département génie industriel ENSA",
  "département génie industriel Fès",
  "génie industriel ENSA Fès",
  "Fès innovation industrielle",
  "Fès technologie 2026",
  "Maroc innovation industrielle",
  "événement ingénierie Fès",
  "événement académique Fès 2026",

  // Filières
  "GESI ENSA Fès",
  "génie énergétique systèmes intelligents",
  "génie énergétique Fès",
  "systèmes intelligents ENSA",
  "génie mécanique ENSA Fès",
  "génie mécanique Fès 2026",
  "génie mécatronique ENSA",
  "GMéca ENSA Fès",
  "génie industriel Fès",
  "GI ENSA Fès",
  "filières ingénierie ENSA Fès",
  "ingénierie énergétique Maroc",
  "ingénierie mécatronique Maroc",

  // Clubs organisateurs
  "Club PowerUP ENSA Fès",
  "PowerUP club ingénierie",
  "club IEC 4.0 ENSA",
  "Engineering Cycle IEC ENSA",
  "club MTZ ENSA Fès",
  "Mécatronics Trendz ENSA",
  "clubs étudiants ENSA Fès",
  "clubs ingénierie Fès",
  "association étudiante ENSA Fès",

  // Programme & dates
  "17 avril 2026 ENSA Fès",
  "18 avril 2026 ENSA Fès",
  "17 18 avril Fès innovation",
  "programme Innov'Industry 2026",
  "programme journée industrielle ENSA",
  "conférences ingénierie Fès 2026",
  "conférences innovation industrielle",
  "conférence énergie systèmes intelligents",
  "conférence mécanique mécatronique",
  "conférence IA IoT industrie 4.0",
  "conférence génie industriel optimisation",
  "conférence entrepreneuriat industriel",
  "table ronde industrie Fès",
  "forum entreprises ENSA Fès",
  "forum recrutement ingénierie Fès",
  "stands filières ENSA",
  "simulation entretien professionnel ENSA",
  "networking ingénierie Fès",
  "remise des prix innovation ENSA",

  // Thèmes techniques
  "intelligence artificielle ingénierie Maroc",
  "IA industrie 4.0 Maroc",
  "IoT systèmes industriels",
  "Internet des objets industrie",
  "industrie 4.0 Maroc",
  "industrie du futur ENSA",
  "industrie du futur Fès",
  "industrie de futur Fès",
  "digitalisation industrie Maroc",
  "digitalisation logistique 4.0",
  "cybersécurité industrielle Maroc",
  "énergies renouvelables ingénierie",
  "efficacité énergétique ENSA",
  "énergie propre innovation Maroc",
  "domotique systèmes intelligents",
  "robotique mécatronique Fès",
  "systèmes embarqués ENSA",
  "électronique puissance ENSA Fès",
  "modélisation systèmes industriels",
  "commande optimisation systèmes",
  "machine learning ingénierie Maroc",
  "big data IoT industrie",
  "vision industrielle IA",
  "diagnostic pronostic systèmes",
  "maintenance industrielle Maroc",
  "gestion production qualité",
  "supply chain ingénierie",
  "développement durable industrie Maroc",
  "fabrication industrielle Fès",
  "procédés industriels ENSA",

  // Participation & inscription
  "inscription Innov'Dom Challenge",
  "inscription compétition ENSA Fès",
  "inscription gratuite innovation",
  "candidature Innov'Dom 2026",
  "soumettre projet ENSA Fès",
  "dépôt dossier compétition Fès",
  "inscription jp4f vercel app",
  "jp4f.vercel.app",
  "plateforme candidature ENSA",
  "deadline 5 avril 2026",
  "date limite candidature ENSA",
  "résultats 10 avril 2026",
  "compétition gratuite étudiants Maroc",
  "participer innovation ENSA Fès",

  // Participants cibles
  "étudiants ingénierie Maroc",
  "étudiants licence master ingénierie",
  "doctorants chercheurs innovation",
  "start-up innovation Maroc",
  "professionnels ingénierie Fès",
  "jeunes ingénieurs Maroc",
  "étudiants ENSA Fès",
  "chercheurs USMBA",

  // Sponsors & partenaires
  "ALTEN Maroc partenaire",
  "Capgemini Maroc partenaire",
  "RADEEF partenaire ENSA",
  "Safran Maroc ingénierie",
  "partenaires industriels ENSA Fès",
  "sponsors innovation Fès 2026",
  "partenariat académique industriel Maroc",
  "Master Tec partenaire ENSA",
  "Cité de l'Innovation Maroc",
  "Université Mohammed V partenaire",

  // Critères & récompenses
  "trophée innovation ENSA Fès",
  "certificat compétition ingénierie",
  "prix innovation industrielle Maroc",
  "récompenses Innov'Dom",
  "jury experts ingénierie Fès",
  "évaluation projets innovants",
  "prototype démo compétition",
  "pitch oral innovation",
  "poster scientifique ENSA",

  // Comité & intervenants
  "Pr Hihi Hicham ENSA Fès",
  "Pr Lahrach ENSA Fès",
  "Pr IJJAALI USMBA",
  "Pr Moustabchir LISA ENSA",
  "laboratoire LISA ENSA Fès",
  "comité scientifique ENSA Fès",
  "comité organisation Innov'Industry",

  // Règlement & conditions
  "règlement Innov'Dom Challenge",
  "règlement compétition ENSA Fès",
  "conditions participation innovation",
  "propriété intellectuelle projet étudiant",
  "code de conduite compétition",
  "modélisation identification systèmes",
  "commande algorithmes apprentissage",
  "formalismes événements discrets",
  "instrumentation industrielle ENSA",
  "supervision industrielle Maroc",
  "traitement image signal ingénierie",
  "sûreté fonctionnement systèmes",
  "gestion maintenance industrielle",
  "gestion projet production Maroc",
  "ingénierie systèmes transport",
  "ingénierie qualité ENSA",
  "systèmes information industrielle",
  "tableaux de bord performance",
  "outils aide décision industrie",
  "systèmes multi-sources énergie",
  "management industriel Maroc",

  // Recherches longue traîne
  "comment participer Innov'Dom Challenge 2026",
  "compétition innovation gratuite étudiants Fès",
  "événement ingénierie ENSA avril 2026",
  "journée innovation industrielle ENSA Fès avril 2026",
  "meilleur événement ingénierie Maroc 2026",
  "conférence innovation technologique Maroc 2026",
  "forum entreprises recrutement ingénierie Fès",
  "soumettre projet innovant ENSA Fès 2026",
  "pitch projet innovation ENSA Fès",
  "réalité augmentée application interactive compétition",
  "projet IoT IA compétition ingénierie Maroc",
  "startup innovation étudiante Maroc 2026",
  "génie industriel événement Maroc 2026",
  "rencontre ingénieurs entreprises Fès 2026",
  "innovation mécatronique ENSA Fès 2026",
  "programme conférences innovation Fès avril",
  "intervenants industrie ENSA Fès 2026",
  "finales compétition technologique ENSA",
  "demi-finale Innov'Dom Challenge",
  "simulation entretien professionnel étudiant Fès",
  "networking ingénieurs Fès avril 2026",
  "innovation énergie propre étudiant Maroc",
  "développement durable industrie étudiant",
  "cybersécurité industrielle compétition Maroc",
  "machine learning IoT projet étudiant Fès",
  "ingénierie systèmes embarqués Maroc",
  "modélisation commande systèmes ENSA Fès",
  "intelligence artificielle apprentissage automatique Fès",
  "industrie futur digitalisation Maroc 2026",
  "forum innovation Fès 2026",
  "partenaires sponsors événement ENSA 2026",
  "inscription compétition innovation Maroc gratuite",
  "Innov'Dom Challenge règlement officiel 2026",
  "J2I JESI 2026 programme détaillé",
  "ENSA Fès calendrier événements 2026",
  "Club PowerUP JESI événement annuel",
  "remise prix trophée ingénierie ENSA",
  "poster scientifique prototype ENSA Fès",
  "appel candidatures compétition technologique gratuite",
  "projet innovant énergie domotique Maroc",
  "Innov'Tech mécatronique robotique Fès",
  "Campus Indus génie industriel 4ème édition",
  "ENSA Fès meilleure école ingénierie Maroc",
  "collaboration académique industrielle Maroc 2026",
  "interdisciplinarité ingénierie ENSA Fès",
  "entrepreneuriat industriel jeunes Maroc",
  "innovation startup étudiant ENSA Fès",
  "innov-indus.vercel.app",
  "site officiel Innov'Industry 2026"
];
