export const SEO_KEYWORDS = [
  "Innov'Industry 2026",
  "Innov'Industry ENSA Fès",
  "journée pédagogique ENSA Fès",
  "journées pédagogiques 4 filières",
  "journée industrielle JESI",
  "journée industrielle ENSA Fès 2026",
  "forum étudiant ENSA Fès",
  "salon étudiant ingénieur Fès",
  "conférence ENSA Fès 2026",
  "Innov'Industry inscription",
  "Innov'Industry programme",
  "Innov'Industry intervenants",
  "Innov'Industry sponsors",
  "Innov'Industry compétition",
  "Innov'Industry orientation",
  "journée portes ouvertes ENSA Fès",
  "forum ingénierie Fès 2026",
  "networking ingénieur Fès",
  "forum emploi ingénieur Maroc",
  "ENSA Fès",
  "ENSAF",
  "JESI ENSA Fès",
  "club JESI",
  "ingénieur état ENSA Fès",
  "formation ingénieur Fès",
  "filières ENSA Fès",
  "génie informatique ENSA Fès",
  "génie électrique ENSA Fès",
  "génie industriel ENSA Fès",
  "génie civil ENSA Fès",
  "bac+5 ingénieur Fès",
  "école ingénieur Fès",
  "powerup club ENSA Fès",
  "vie étudiante ENSA Fès",
  "actualité ENSA Fès",
  "orientation filière ingénieur Maroc",
  "choisir filière ingénieur ENSA",
  "débouchés génie informatique Maroc",
  "carrière ingénieur Maroc",
  "emploi ingénieur Maroc 2026",
  "stage ingénieur Fès",
  "stage ingénieur Maroc 2026",
  "salaire ingénieur Maroc",
  "marché emploi ingénieur Maroc",
  "offre emploi ingénieur Fès",
  "débouchés génie civil Maroc",
  "débouchés génie industriel Maroc",
  "débouchés génie électrique Maroc",
  "compétences ingénieur 2026",
  "intelligence artificielle métiers Maroc",
  "data science emploi Maroc",
  "Capgemini Maroc recrutement",
  "Safran Maroc ingénieur",
  "Alten Maroc stage",
  "entreprise partenaire ENSA Fès",
  "partenariat industriel ENSA Fès",
  "entreprise tech Fès",
  "Green Energy Park Maroc",
  "Cité innovation Fès",
  "UM5 Rabat partenariat",
  "écosystème startup Maroc",
  "multinationale Maroc ingénieur",
  "recruteur ingénieur Fès",
  "intelligence artificielle Maroc 2026",
  "machine learning Maroc formation",
  "data science Maroc étudiant",
  "cloud computing Maroc ingénieur",
  "cybersécurité Maroc formation",
  "IoT Maroc ingénieur",
  "industrie 4.0 Maroc",
  "transformation digitale Maroc",
  "énergie renouvelable Maroc ingénieur",
  "smart city Maroc",
  "ingénierie logicielle Maroc",
  "automatisme Maroc ingénieur",
  "réseaux télécommunications Maroc",
  "lean manufacturing Maroc",
  "supply chain Maroc ingénieur",
  "hackathon ENSA Fès",
  "quiz ingénieur Maroc",
  "challenge étudiant Maroc",
  "pitch startup étudiant Maroc",
  "club robotique ENSA",
  "club développement web ENSA",
  "club énergie ENSA",
  "association étudiante ENSA Fès",
  "workshop étudiant Fès",
  "masterclass ingénieur Maroc",
  "simulation entretien étudiant",
  "atelier CV ingénieur Maroc",
  "compétition étudiante Maroc",
  "comment choisir sa filière à ENSA Fès",
  "quelles sont les filières de ENSA Fès",
  "programme journée pédagogique ENSA Fès 2026",
  "comment s'inscrire Innov'Industry 2026",
  "débouchés filière génie informatique ENSA Fès",
  "meilleure filière ingénieur au Maroc",
  "salaire ingénieur débutant Maroc 2026",
  "comment trouver stage ingénieur Fès",
  "entreprises qui recrutent ingénieurs Fès",
  "événements étudiants Fès mars 2026",
  "compétition ingénieur Maroc 2026"
];
